### ISSUE TITLE
Search for project not working in Microsoft Edge

### ISSUE THREAD

**Issue by sgwinder** [OutdoorRD/trails-viz#109]
From Ryan Balkcom on 5/26/20: "I tried to open the dashboard in Microsoft Edge today and I was able to click on the search bar and the two OKAWEN options showed up, but I couldn't press enter to search for some reason."

**Comment by vivekkr12** [comment]
The feature is implemented using a feature which is not supported by Microsoft Edge versions <= 18. Newer versions of edge which were released post January 2020 support this.

Looking for alternatives which could work in the previous ones as well.

**Comment by sgwinder** [comment]
Thanks for looking into this Vivek! I don't see this as a high priority issue to solve, especially if the newest version of Edge supports the feature. In the meantime we can keep pushing people towards Chrome and Firefox.
