### ISSUE TITLE
Mapbox classic is deprecated.  Update to modern API.

### ISSUE THREAD

**Issue by woodsp** [OutdoorRD/trails-viz#124]
Basemap is broken because mapbox [deprecated the classic API](https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4).

The new "modern styles" API has [equivalent layers](https://docs.mapbox.com/api/maps/#mapbox-styles) with a [slightly different API request for leaflet](https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/#leaflet-implementations).

**Comment by sgwinder** [comment]
Hey @woodsp @aromatic-toast , the basemap still isn't loading for me when I first access a project (eg go to "trailtrends.outdoorrd.org" and enter "Western Washington"). If I refresh the page the basemap loads.

**Comment by sgwinder** [comment]
Hey @woodsp, did you update the basemap under the Home Locations widget with your previous commit here? It's not loading for me now.
