### ISSUE TITLE
Dashboard(s) for multiple projects

### ISSUE THREAD

**Issue by woodsp** [OutdoorRD/trails-viz#15]
Eventually we'll want to display on-site and modeled estimates for sites in other "projects" -- eg, sites within MBS, or sites from NM, in addition to the Middle Fork.

This probably requires thinking now about whether we want to deploy multiple project-specific dashboards on different URLs versus a single dashboard capable of switching the visuals among projects.

**Comment by davemfish** [comment]
Yes, this is an important point. It seems like on the data collection and modeling end, we're building a database that has all projects lumped together. So we could envision an API endpoint that takes a "project" parameter and calls a function to return only data for that project to the dashboard. 

I think that would mean a unique URL for each dashboard (e.g. vulpes.sefs.uw.edu/trails-viz/middle-fork). That might make it easy for us to switch from project to project, but also not immediately obvious to anyone else who only cares about one project.

**Comment by sgwinder** [comment]
It might also be useful to be able to filter by "Unit". Probably as a second layer under filtering by "project".

**Comment by woodsp** [comment]
Hey @vivekkr12, the "Project Search" box should present every project that contains one of our PROJECT_GROUPS.  Eg, a user searching for "MBS", would have to choose between "MBS_PIL" and "MBS_SARL" (currently).

**Comment by vivekkr12** [comment]
Implemented after code refactoring. Project group config changed to search for individual MBS projects
