### ISSUE TITLE
test browser and device compatibility

### ISSUE THREAD

**Issue by davemfish** [OutdoorRD/trails-viz#2]
So far I've only developed against Chrome, and tested with Chrome and Firefox. Are there special ways to ensure compatibility with IE/Edge?

How does the page look on mobile devices?

**Comment by davemfish** [comment]
I notice some different functionality on Chrome vs Firefox. In Firefox, the linking between map and dropdown box doesn't work. Also the leaflet onclick popup appears in FF but not in Chrome (best without the popup I think). 

I don't mind telling our friends that should always use Chrome to view the app, for the time being.

**Comment by vivekkr12** [comment]
Using Vue Js now which handles browser and device compatibility.
