### ISSUE TITLE
Display the polygon representation of each trail/site

### ISSUE THREAD

**Issue by davemfish** [OutdoorRD/trails-viz#23]
We all agree that line segments look nice and are most intuitive for trails. But the data we display is truly representative of an area, not a line. So an option to display that area for each trail might be nice. A couple ideas:

Map the polygons as well as the lines, but keep polygons completely transparent until the mouse hovers over, then make that polygon appear, and also make it clickable just like the line. That also solves the problem of the lines being a little tough to click on since they are a very small target.

Another option is to add the polygons as another layer, with a leaflet layer menu that allows toggling layers on and off. The polygons would probably be off by default.

**Comment by davemfish** [comment]
Need to re-implement this in the flask app. All the necessary js code is in trail-map.js and commented out. views.py needs to return geojson polygons, probably from the api/geojson endpoint. Though that gets slightly tricky...will need to concat line and polygon json since we can only return a single string from a flask endpoint. Then we'll need to split the string on the js side. But that approach should allow re-use of all the existing trail-map.js code.

**Comment by woodsp** [comment]
We want polygons to appear on initial page load along with lines.

And display any site that has a polygon or line AND data in the weekly/monthly tables.
