### ISSUE TITLE
Zoom in feature for X axis from Monthly to Weekly scale 

### ISSUE THREAD

**Issue by EmiliaH** [OutdoorRD/trails-viz#26]
It would be nice to have the option (or make it automatic) so that when you zoom in on the x axis the graph goes from showing monthly estimates to weekly estimates. This would allow us to show more of the on-site data for more trails (it is missing on some trails since there are not enough days of data to create monthly estimates).

**Comment by woodsp** [comment]
This would involve sourcing the weekly data table to fill in the plots, obviously.

@sgwinder: currently, the monthly data are drawn from the monthly data table (not the weekly data table).  Is that correct?  Or should we sum the weekly values?

**Comment by sgwinder** [comment]
Yes, that's correct. The modeling script currently does the summing up of weekly values to produce the mmm tables. I'm not sure if that's a good long term solution or whether we should just move it to the website side... The reason to keep it in the modeling script in my mind is that it is dropping months with fewer than 3 weeks of data right now (though actually, this isn't true in the current tables you're working with). The "www" tables in the i90 branch should be up to date.

**Comment by woodsp** [comment]
Scratch that; we changed our minds.  Now we prefer a radio box to select weekly vs monthly on the time series plot.

**Comment by vivekkr12** [comment]
Option added to manually switch from monthly to weekly in time series  https://github.com/OutdoorRD/trails-viz/commit/251c21495c30c3a2a22ca9907bc8d28c64e87425
