### ISSUE TITLE
map needs more reference info

### ISSUE THREAD

**Issue by davemfish** [OutdoorRD/trails-viz#3]
Feedback from SL and AW was that the map grabs attention right away, and therefore should have more familiar features on it to help orient people. Maybe trailhead points, roads, placenmaes, etc.

**Comment by davemfish** [comment]
Trailhead points would help orient people, and make it clear which direction hikers are moving. This might require maintaining a point dataset, keyed by alltrls_id, alongside the lines dataset, as I can think of no way to automatically generate trailhead points from the lines.

**Comment by davemfish** [comment]
Switching our basemap to Mapbox's Outdoors layer will satisfy some of this. I will push a branch that uses that layer, and includes some adjustments to the line styles to.

**Comment by sgwinder** [comment]
Update Mapbox's Outdoors layer to be the current version

**Comment by vivekkr12** [comment]
Updated mapbox version.
