### ISSUE TITLE
Change map to display trailhead points first

### ISSUE THREAD

**Issue by sgwinder** [OutdoorRD/trails-viz#33]
Trailhead points should be the primary marker for sites. Then, when you hover over one of them, the site line and polygon should appear (and stay if you click on the site).

Color these by visitation (popularity) in 3 levels. So low use sites are blue, medium use is yellow, and high use is red.

Later, it would also be nice to aggregate those sites into a single point if you are zoomed out (like is implemented on wta.org and alltrails.com).

**Comment by vivekkr12** [comment]
After this feature is implemented, the thickness would be line would be same. The visitation count would be displayed the color of the trail head.

**Comment by woodsp** [comment]
FYI, the points file is called allsites_access_points.geojson

**Comment by sgwinder** [comment]
We don't have points for all sites, so closing this issue.
