### ISSUE TITLE
Replace logos and add acknowledgements

### ISSUE THREAD

**Issue by woodsp** [OutdoorRD/trails-viz#47]
Logos in the footer need to go.  Footer will be replaced with link to Outdoor R&D and we'll add a tab or page with partner info and acknowledgments.

**Comment by woodsp** [comment]
Hey @vivekkr12, will you please replace the footer logos with "Created by Outdoor R&D" that links to www.outdoorrd.org?  Keep all logos in trails-viz-zpp/src/assets because we'll use them later on an acknowledgements page.

**Comment by vivekkr12** [comment]
The footer has been removed and a link to outdoorrd.org has been added in the landing page

**Comment by sgwinder** [comment]
Project info tabs have some acknowledgements, which feels sufficient for now.
