### ISSUE TITLE
Project landing pages should show project summaries for each component plot

### ISSUE THREAD

**Issue by sgwinder** [OutdoorRD/trails-viz#48]
So, 
1. the bar chart should show visitors to the entire project region (summed across sites, then take the various averages [average per year, per month, etc])
2. The time series should show the total number of modeled visitors, and each social media platform (summed across sites). Do not include on-site visitors in this one.
3. The home locations treemap should show the total number of visitor-days from each county/state, summed across sites.

**Comment by vivekkr12** [comment]
Implemented in commit - https://github.com/OutdoorRD/trails-viz/commit/24954345b66f690d18f64377118badf2f690880e
