### ISSUE TITLE
Home locations as a map

### ISSUE THREAD

**Issue by woodsp** [OutdoorRD/trails-viz#49]
We wire-framed an idea for a new tab containing a map of visitor origins.  Some rough ideas at this point are:
- map shows proportion of visitors who originate from each census tract
- as points either sized or colored by proportion of visitors (at census tract centroid)
- only census tracts from WA
- on a solid-color basemap, with political boundaries and census tract boundaries
- with an accompanying table showing proportions of visitors per age, income, and race/ethnic group
- clicking on a census tract in the (child) map would update the table

**Comment by sgwinder** [comment]
Add legend to map. 
Also, it would be cool to start at the country level (showing visit days from each state). Then clicking on a state could zoom in and show visit days from each county. Then, clicking on a WA county could zoom in again to census tract.
