### ISSUE TITLE
Reorganize widget tabs and add info tabs for both visitation and home locations

### ISSUE THREAD

**Issue by sgwinder** [OutdoorRD/trails-viz#55]
Let's combine the tabs to the right of the map. So we want
1. Info (for the project level readme)
2. Visitation
    a) Info (about the visitation estimates, social media, and model)
    b) bar graph
    c) time series
3. Home locations
    a) Info (about the home location calculations, that we are presenting visit days, not unique visitors)
    b) Treemap
    c) home locations map
    d) demographics summaries

**Comment by woodsp** [comment]
Also, we'd like to be able to add images to info pages via markdown.
