### ISSUE TITLE
Clean up landing page

### ISSUE THREAD

**Issue by sgwinder** [OutdoorRD/trails-viz#56]
Move the project search bar into the middle of the landing page, and get rid of the (currently empty) map. When you choose a project then the map and widgets to the right can return.

This will also want some info about the project written up for the landing page (Sama todo).

**Comment by woodsp** [comment]
Next TODOs: @woodsp will edit the landing page next while @vivekkr12 adds a background image.

**Comment by woodsp** [comment]
Reopening in order to address a couple more TODOs, above.
