### ISSUE TITLE
Add King County as additional project

### ISSUE THREAD

**Issue by sgwinder** [OutdoorRD/trails-viz#75]
Data files have been uploaded to the data repo - let's get them into the dashboard!

**Comment by woodsp** [comment]
Please also document the process so we know how for future projects.

See Issue #61.

**Comment by woodsp** [comment]
See OutdoorRD/trails-viz-data#5 for data.

**Comment by vivekkr12** [comment]
> Please also document the process so we know how for future projects.
> 
> See Issue #61.

https://github.com/OutdoorRD/trails-viz/wiki/Adding-New-Project
