### ISSUE TITLE
Alternative visualization option for hierarchical tabs

### ISSUE THREAD

**Issue by vivekkr12** [OutdoorRD/trails-viz#80]
Tabs within tabs looks clunky. Need to have a different way to have the same features.
To display the options we can use drop downs.

We also need an option to return back to the project level. We can use bread crums where we currently show site name for it.

**Comment by sgwinder** [comment]
Also, change the name of the sub info tabs (eg the Visitation Info tab and the Visitor Characteristic Info tab) to be "Methods".

**Comment by sgwinder** [comment]
And rename "Home Counties" to "Home Locations".
