### ISSUE TITLE
Display home locations on multiple level the Home Locations Map (state -> county -> census tract)

### ISSUE THREAD

**Issue by sgwinder** [OutdoorRD/trails-viz#84]
The home locs map should start by displaying counts for entire counties, for the state which the project is in (eg Washington). Then, if you click on a county, the map should zoom in and display the census tract-level counts.

**Comment by vivekkr12** [comment]
The first load will be home locations on state level. On click of a state the zoom level will become county level for that state. On click of a county the zoom level would become census tract level for that county.

Reverting back to higher zoom level would be based on the zoom level of map.
